# (category, name, github owner/repo or None, npm package or None)
ITEMS = [
 # 24 auth UI / auth SDK
 ("24","Better Auth","better-auth/better-auth","better-auth"),
 ("24","Auth.js (NextAuth)","nextauthjs/next-auth","next-auth"),
 ("24","Clerk React (SDK)","clerk/javascript","@clerk/react"),
 ("24","Supabase Auth UI React","supabase-community/auth-ui","@supabase/auth-ui-react"),
 ("24","Lucia (guide)","lucia-auth/lucia",None),
 ("24","@oslojs/crypto (oslo 后继)","oslo-project/crypto","@oslojs/crypto"),
 ("24","Arctic (OAuth 2)","pilcrowonpaper/arctic","arctic"),
 ("24","jose (JWT)","panva/jose","jose"),
 ("24","oidc-client-ts","authts/oidc-client-ts","oidc-client-ts"),
 ("24","react-oidc-context","authts/react-oidc-context","react-oidc-context"),
 ("24","Keycloak JS","keycloak/keycloak","keycloak-js"),
 ("24","Firebase UI Web","firebase/firebaseui-web","firebaseui"),
 ("24","Ory Elements","ory/elements","@ory/elements-react"),
 ("24","SimpleWebAuthn (browser)","MasterKale/SimpleWebAuthn","@simplewebauthn/browser"),
 ("24","Auth0 SPA JS","auth0/auth0-spa-js","@auth0/auth0-spa-js"),
 ("24","Logto React","logto-io/js","@logto/react"),
 ("24","Hanko Elements","teamhanko/hanko","@teamhanko/hanko-elements"),
 ("24","Zitadel React","zitadel/zitadel-react","@zitadel/react"),
 # 25 payments UI
 ("25","Stripe React","stripe/react-stripe-js","@stripe/react-stripe-js"),
 ("25","stripe-js","stripe/stripe-js","@stripe/stripe-js"),
 ("25","PayPal React","paypal/paypal-js","@paypal/react-paypal-js"),
 ("25","Paddle JS","PaddleHQ/paddle-js-wrapper","@paddle/paddle-js"),
 ("25","LemonSqueezy JS","lmsqueezy/lemonsqueezy.js","@lemonsqueezy/lemonsqueezy.js"),
 ("25","Polar","polarsource/polar","@polar-sh/sdk"),
 ("25","Braintree Web Drop-in","braintree/braintree-web-drop-in","braintree-web-drop-in"),
 ("25","Adyen Web","Adyen/adyen-web","@adyen/adyen-web"),
 ("25","react-credit-cards-2","amarofashion/react-credit-cards","react-credit-cards-2"),
 ("25","card-validator","braintree/card-validator","card-validator"),
 ("25","Autumn (billing)","useautumn/autumn","autumn-js"),
 ("25","Creem","armitage-labs/creem-sdk","creem"),
 # 26 AI frontend
 ("26","Vercel AI SDK","vercel/ai","ai"),
 ("26","@ai-sdk/react","vercel/ai","@ai-sdk/react"),
 ("26","assistant-ui","assistant-ui/assistant-ui","@assistant-ui/react"),
 ("26","CopilotKit","CopilotKit/CopilotKit","@copilotkit/react-core"),
 ("26","LangChain.js","langchain-ai/langchainjs","langchain"),
 ("26","LlamaIndex.TS","run-llama/LlamaIndexTS","llamaindex"),
 ("26","Transformers.js","huggingface/transformers.js","@huggingface/transformers"),
 ("26","WebLLM","mlc-ai/web-llm","@mlc-ai/web-llm"),
 ("26","ONNX Runtime Web","microsoft/onnxruntime","onnxruntime-web"),
 ("26","TensorFlow.js","tensorflow/tfjs","@tensorflow/tfjs"),
 ("26","MediaPipe Tasks Vision","google-ai-edge/mediapipe","@mediapipe/tasks-vision"),
 ("26","Deep Chat","OvidijusParsiunas/deep-chat","deep-chat-react"),
 ("26","NLUX","nlkitai/nlux","@nlux/react"),
 ("26","LobeHub UI","lobehub/lobe-ui","@lobehub/ui"),
 ("26","Ant Design X","ant-design/x","@ant-design/x"),
 ("26","Chatbot UI (Mckay)","mckaywrigley/chatbot-ui",None),
 ("26","Vercel AI Elements","vercel/ai-elements","ai-elements"),
 ("26","ai-sdk-ui (shadcn ai)","shadcn-ui/ui","shadcn"),
 ("26","OpenAI Node","openai/openai-node","openai"),
 ("26","Anthropic SDK TS","anthropics/anthropic-sdk-typescript","@anthropic-ai/sdk"),
 ("26","eventsource-parser","rexxars/eventsource-parser","eventsource-parser"),
 ("26","@microsoft/fetch-event-source","Azure/fetch-event-source","@microsoft/fetch-event-source"),
 ("26","Mastra","mastra-ai/mastra","@mastra/core"),
 ("26","Streamdown (见 §8)",None,None),
 # 27 micro frontends
 ("27","Module Federation (core)","module-federation/core","@module-federation/enhanced"),
 ("27","@originjs/vite-plugin-federation","originjs/vite-plugin-federation","@originjs/vite-plugin-federation"),
 ("27","single-spa","single-spa/single-spa","single-spa"),
 ("27","qiankun (蚂蚁)","umijs/qiankun","qiankun"),
 ("27","Garfish (字节)","web-infra-dev/garfish","garfish"),
 ("27","wujie 无界 (腾讯)","Tencent/wujie","wujie"),
 ("27","micro-app (京东)","jd-opensource/micro-app","@micro-zoe/micro-app"),
 ("27","Piral","smapiot/piral","piral"),
 ("27","Bit","teambit/bit","@teambit/bit"),
 ("27","import-maps polyfill (es-module-shims)","guybedford/es-module-shims","es-module-shims"),
 ("27","Native Federation (Angular Architects)","angular-architects/module-federation-plugin","@angular-architects/native-federation"),
 ("27","zoid (PayPal)","krakenjs/zoid","zoid"),
 # 28 performance monitoring / error tracking / analytics
 ("28","web-vitals","GoogleChrome/web-vitals","web-vitals"),
 ("28","Sentry Browser","getsentry/sentry-javascript","@sentry/browser"),
 ("28","@sentry/react","getsentry/sentry-javascript","@sentry/react"),
 ("28","OpenTelemetry Web","open-telemetry/opentelemetry-js","@opentelemetry/sdk-trace-web"),
 ("28","Grafana Faro","grafana/faro-web-sdk","@grafana/faro-web-sdk"),
 ("28","PostHog JS","PostHog/posthog-js","posthog-js"),
 ("28","Plausible tracker","plausible/plausible-tracker","plausible-tracker"),
 ("28","Umami","umami-software/umami",None),
 ("28","rrweb (会话回放)","rrweb-io/rrweb","rrweb"),
 ("28","OpenReplay tracker","openreplay/openreplay","@openreplay/tracker"),
 ("28","Highlight.run","highlight/highlight","highlight.run"),
 ("28","Lighthouse","GoogleChrome/lighthouse","lighthouse"),
 ("28","unlighthouse","harlan-zw/unlighthouse","unlighthouse"),
 ("28","perfume.js","Zizzamia/perfume.js","perfume.js"),
 ("28","Partytown","QwikDev/partytown","@qwik.dev/partytown"),
 ("28","why-did-you-render","welldone-software/why-did-you-render","@welldone-software/why-did-you-render"),
 ("28","React Scan","aidenybai/react-scan","react-scan"),
 ("28","Million.js","aidenybai/million","million"),
 ("28","Vercel Analytics","vercel/analytics","@vercel/analytics"),
 ("28","Vercel Speed Insights","vercel/speed-insights","@vercel/speed-insights"),
 ("28","Bugsnag JS","bugsnag/bugsnag-js","@bugsnag/js"),
 ("28","GlitchTip / Sentry compat",None,None),
 # 29 visual builders / page builders / low-code
 ("29","Puck","puckeditor/puck","@puckeditor/core"),
 ("29","craft.js","prevwong/craft.js","@craftjs/core"),
 ("29","GrapesJS","GrapesJS/grapesjs","grapesjs"),
 ("29","Builder.io SDK React","BuilderIO/builder","@builder.io/react"),
 ("29","Plasmic","plasmicapp/plasmic","@plasmicapp/loader-react"),
 ("29","Webstudio","webstudio-is/webstudio",None),
 ("29","react-email","resend/react-email","@react-email/components"),
 ("29","MJML","mjmlio/mjml","mjml"),
 ("29","Unlayer (react-email-editor)","unlayer/react-email-editor","react-email-editor"),
 ("29","Easy Email","zalify/easy-email","easy-email-editor"),
 ("29","Form.io React","formio/react","@formio/react"),
 ("29","SurveyJS (form library)","surveyjs/survey-library","survey-react-ui"),
 ("29","react-jsonschema-form","rjsf-team/react-jsonschema-form","@rjsf/core"),
 ("29","Formily (阿里)","alibaba/formily","@formily/react"),
 ("29","amis (百度)","baidu/amis","amis"),
 ("29","LowCodeEngine (阿里)","alibaba/lowcode-engine","@alilc/lowcode-engine"),
 ("29","Tmagic Editor (腾讯)","Tencent/tmagic-editor","@tmagic/editor"),
 ("29","React Flow (xyflow)","xyflow/xyflow","@xyflow/react"),
 ("29","Rete.js","retejs/rete","rete"),
 ("29","LogicFlow (滴滴)","didi/LogicFlow","@logicflow/core"),
 ("29","AntV X6","antvis/X6","@antv/x6"),
 ("29","JointJS","clientIO/joint","@joint/core"),
 ("29","react-grid-layout","react-grid-layout/react-grid-layout","react-grid-layout"),
 ("29","Gridstack","gridstack/gridstack.js","gridstack"),
 ("29","react-mosaic","nomcopter/react-mosaic","react-mosaic-component"),
 ("29","dockview","mathuo/dockview","dockview"),
 # 30 server-side rendering to image / OG / PDF / screenshots
 ("30","Satori (Vercel)","vercel/satori","satori"),
 ("30","@vercel/og","vercel/next.js","@vercel/og"),
 ("30","resvg-js","thx/resvg-js","@resvg/resvg-js"),
 ("30","sharp","lovell/sharp","sharp"),
 ("30","jimp","jimp-dev/jimp","jimp"),
 ("30","@napi-rs/canvas","Brooooooklyn/canvas","@napi-rs/canvas"),
 ("30","node-canvas","Automattic/node-canvas","canvas"),
 ("30","skia-canvas","samizdatco/skia-canvas","skia-canvas"),
 ("30","Puppeteer","puppeteer/puppeteer","puppeteer"),
 ("30","Playwright (截图, 见 §14)",None,None),
 ("30","html-to-image","bubkoo/html-to-image","html-to-image"),
 ("30","modern-screenshot","qq15725/modern-screenshot","modern-screenshot"),
 ("30","dom-to-image-more","1904labs/dom-to-image-more","dom-to-image-more"),
 ("30","takumi (Rust satori)","kane50613/takumi","@takumi-rs/core"),
 ("30","og-image (workers-og)","kvnang/workers-og","workers-og"),
 ("30","pdfmake","bpampuch/pdfmake","pdfmake"),
 ("30","jsPDF","parallax/jsPDF","jspdf"),
 ("30","Gotenberg","gotenberg/gotenberg",None),
 # 31 HTTP / utility functions / data structures
 ("31","ky (见 §0)","sindresorhus/ky","ky"),
 ("31","ofetch","unjs/ofetch","ofetch"),
 ("31","wretch","elbywan/wretch","wretch"),
 ("31","up-fetch","L-Blondy/up-fetch","up-fetch"),
 ("31","better-fetch","Bekacru/better-fetch","@better-fetch/fetch"),
 ("31","es-toolkit","toss/es-toolkit","es-toolkit"),
 ("31","lodash","lodash/lodash","lodash"),
 ("31","lodash-es",None,"lodash-es"),
 ("31","Radash","sodiray/radash","radash"),
 ("31","remeda","remeda/remeda","remeda"),
 ("31","Ramda","ramda/ramda","ramda"),
 ("31","Effect","Effect-TS/effect","effect"),
 ("31","neverthrow","supermacro/neverthrow","neverthrow"),
 ("31","ts-pattern","gvergnaud/ts-pattern","ts-pattern"),
 ("31","type-fest","sindresorhus/type-fest","type-fest"),
 ("31","immer","immerjs/immer","immer"),
 ("31","mutative","unadlib/mutative","mutative"),
 ("31","nanoid","ai/nanoid","nanoid"),
 ("31","uuid","uuidjs/uuid","uuid"),
 ("31","ulid","ulid/javascript","ulid"),
 ("31","p-limit","sindresorhus/p-limit","p-limit"),
 ("31","p-queue","sindresorhus/p-queue","p-queue"),
 ("31","p-retry","sindresorhus/p-retry","p-retry"),
 ("31","superjson","flightcontrolhq/superjson","superjson"),
 ("31","devalue","Rich-Harris/devalue","devalue"),
 ("31","fast-deep-equal","epoberezkin/fast-deep-equal","fast-deep-equal"),
 ("31","dequal","lukeed/dequal","dequal"),
 ("31","big.js","MikeMcl/big.js","big.js"),
 ("31","decimal.js","MikeMcl/decimal.js","decimal.js"),
 ("31","dinero.js","dinerojs/dinero.js","dinero.js"),
 ("31","currency.js","scurker/currency.js","currency.js"),
 ("31","fuse.js","krisk/Fuse","fuse.js"),
 ("31","minisearch","lucaong/minisearch","minisearch"),
 ("31","Orama","oramasearch/orama","@orama/orama"),
 ("31","FlexSearch","nextapps-de/flexsearch","flexsearch"),
 ("31","match-sorter","kentcdodds/match-sorter","match-sorter"),
 ("31","comlink","GoogleChromeLabs/comlink","comlink"),
 ("31","mitt","developit/mitt","mitt"),
 ("31","nanoevents","ai/nanoevents","nanoevents"),
 ("31","eventemitter3","primus/eventemitter3","eventemitter3"),
 ("31","query-string","sindresorhus/query-string","query-string"),
 ("31","qs","ljharb/qs","qs"),
 ("31","js-cookie","js-cookie/js-cookie","js-cookie"),
 ("31","copy-to-clipboard","sudodoki/copy-to-clipboard","copy-to-clipboard"),
 ("31","validator.js","validatorjs/validator.js","validator"),
 ("31","libphonenumber-js","catamphetamine/libphonenumber-js","libphonenumber-js"),
 ("31","DOMPurify","cure53/DOMPurify","dompurify"),
 ("31","sanitize-html","apostrophecms/sanitize-html","sanitize-html"),
 ("31","he (HTML entities)","mathiasbynens/he","he"),
 ("31","marked","markedjs/marked","marked"),
 ("31","markdown-it","markdown-it/markdown-it","markdown-it"),
 ("31","Papa Parse (CSV)","mholt/PapaParse","papaparse"),
 ("31","SheetJS (xlsx CE)","SheetJS/sheetjs","xlsx"),
 ("31","ExcelJS","exceljs/exceljs","exceljs"),
 ("31","yaml","eemeli/yaml","yaml"),
 ("31","chroma.js","gka/chroma.js","chroma-js"),
 ("31","colord","omgovich/colord","colord"),
 ("31","culori","Evercoder/culori","culori"),
 ("31","pretty-bytes","sindresorhus/pretty-bytes","pretty-bytes"),
 ("31","filesize","avoidwork/filesize.js","filesize"),
 ("31","hotkeys-js","jaywcjlove/hotkeys-js","hotkeys-js"),
 ("31","tinykeys","jamiebuilds/tinykeys","tinykeys"),
 ("31","react-hotkeys-hook","JohannesKlauss/react-hotkeys-hook","react-hotkeys-hook"),
 ("31","idb (见 §23)",None,None),
 # 32 images / media / video / audio
 ("32","react-image-crop","DominicTobias/react-image-crop","react-image-crop"),
 ("32","react-easy-crop","ValentinH/react-easy-crop","react-easy-crop"),
 ("32","Cropper.js","fengyuanchen/cropperjs","cropperjs"),
 ("32","react-advanced-cropper","advanced-cropper/react-advanced-cropper","react-advanced-cropper"),
 ("32","browser-image-compression","Donaldcwl/browser-image-compression","browser-image-compression"),
 ("32","compressorjs","fengyuanchen/compressorjs","compressorjs"),
 ("32","Squoosh (libs)","GoogleChromeLabs/squoosh",None),
 ("32","@jsquash/webp","jamsinclair/jSquash","@jsquash/webp"),
 ("32","exifr","MikeKovarik/exifr","exifr"),
 ("32","heic2any","alexcorvi/heic2any","heic2any"),
 ("32","yet-another-react-lightbox","igordanchenko/yet-another-react-lightbox","yet-another-react-lightbox"),
 ("32","PhotoSwipe","dimsemenov/PhotoSwipe","photoswipe"),
 ("32","react-photo-album","igordanchenko/react-photo-album","react-photo-album"),
 ("32","react-zoom-pan-pinch","BetterTyped/react-zoom-pan-pinch","react-zoom-pan-pinch"),
 ("32","Swiper","nolimits4web/swiper","swiper"),
 ("32","Embla (见 §0)",None,None),
 ("32","Keen Slider","rcbyr/keen-slider","keen-slider"),
 ("32","unpic (响应式图片)","ascorbic/unpic-img","@unpic/react"),
 ("32","vite-imagetools","JonasKruckenberg/imagetools","vite-imagetools"),
 ("32","Video.js","videojs/video.js","video.js"),
 ("32","Plyr","sampotts/plyr","plyr"),
 ("32","Vidstack","vidstack/player","@vidstack/react"),
 ("32","react-player","cookpete/react-player","react-player"),
 ("32","hls.js","video-dev/hls.js","hls.js"),
 ("32","dash.js","Dash-Industry-Forum/dash.js","dashjs"),
 ("32","Shaka Player","shaka-project/shaka-player","shaka-player"),
 ("32","Howler.js","goldfire/howler.js","howler"),
 ("32","Tone.js","Tonejs/Tone.js","tone"),
 ("32","wavesurfer.js","katspaugh/wavesurfer.js","wavesurfer.js"),
 ("32","Peaks.js (BBC)","bbc/peaks.js","peaks.js"),
 ("32","ffmpeg.wasm","ffmpegwasm/ffmpeg.wasm","@ffmpeg/ffmpeg"),
 ("32","mediabunny","Vanilagy/mediabunny","mediabunny"),
 ("32","Remotion","remotion-dev/remotion","remotion"),
 ("32","react-webcam","mozmorris/react-webcam","react-webcam"),
 ("32","html5-qrcode","mebjas/html5-qrcode","html5-qrcode"),
 ("32","zxing-wasm","Sec-ant/zxing-wasm","zxing-wasm"),
 ("32","qr-scanner","nimiq/qr-scanner","qr-scanner"),
 ("32","react-pdf-highlighter (见 §10)",None,None),
 ("32","Motion Canvas","motion-canvas/motion-canvas","@motion-canvas/core"),
 ("32","Lottie (见 §4)",None,None),
 # 33 notifications / toast / feedback
 ("33","sonner (见 §0)","emilkowalski/sonner","sonner"),
 ("33","react-hot-toast (见 §0)","timolins/react-hot-toast","react-hot-toast"),
 ("33","react-toastify","fkhadra/react-toastify","react-toastify"),
 ("33","notistack","iamhosseindhv/notistack","notistack"),
 ("33","Notyf","caroso1222/notyf","notyf"),
 ("33","Toastify JS","apvarun/toastify-js","toastify-js"),
 ("33","Notiflix","notiflix/Notiflix","notiflix"),
 ("33","SweetAlert2","sweetalert2/sweetalert2","sweetalert2"),
 ("33","Push.js (Web Push)","Nickersoft/push.js","push.js"),
 ("33","NProgress","rstacruz/nprogress","nprogress"),
 ("33","react-top-loading-bar","klendi/react-top-loading-bar","react-top-loading-bar"),
 ("33","Novu (in-app inbox)","novuhq/novu","@novu/react"),
 ("33","Knock React","knocklabs/javascript","@knocklabs/react"),
 ("33","react-loading-skeleton","dvtng/react-loading-skeleton","react-loading-skeleton"),
 ("33","react-spinners","davidhu2000/react-spinners","react-spinners"),
 ("33","canvas-confetti","catdad/canvas-confetti","canvas-confetti"),
 ("33","react-confetti","alampros/react-confetti","react-confetti"),
 ("33","Shepherd (产品导览)","shepherd-pro/shepherd","shepherd.js"),
 ("33","driver.js","kamranahmedse/driver.js","driver.js"),
 ("33","intro.js","usablica/intro.js","intro.js"),
 ("33","react-joyride","gilbarbara/react-joyride","react-joyride"),
 ("33","Onborda (Next/Tailwind)","uixmat/onborda","onborda"),
 ("33","NextStepjs","enszrlu/NextStep","nextstepjs"),
 ("33","react-tooltip","ReactTooltip/react-tooltip","react-tooltip"),
 ("33","Tippy.js","atomiks/tippyjs","tippy.js"),
 ("33","Floating UI","floating-ui/floating-ui","@floating-ui/react"),
 # 34 command palette / search UI / keyboard
 ("34","cmdk (见 §0)","pacocoursey/cmdk","cmdk"),
 ("34","kbar","timc1/kbar","kbar"),
 ("34","react-cmdk","albingroen/react-cmdk","react-cmdk"),
 ("34","ninja-keys","ssleptsov/ninja-keys","ninja-keys"),
 ("34","command-score","superhuman/command-score","command-score"),
 ("34","Pagefind","Pagefind/pagefind","pagefind"),
 ("34","DocSearch (Algolia)","algolia/docsearch","@docsearch/react"),
 ("34","Algolia autocomplete","algolia/autocomplete","@algolia/autocomplete-js"),
 ("34","InstantSearch React","algolia/instantsearch","react-instantsearch"),
 ("34","Typesense InstantSearch adapter","typesense/typesense-instantsearch-adapter","typesense-instantsearch-adapter"),
 ("34","Meilisearch JS","meilisearch/meilisearch-js","meilisearch"),
 ("34","react-select","JedWatson/react-select","react-select"),
 ("34","downshift","downshift-js/downshift","downshift"),
 ("34","react-mentions (仓库已删除)",None,"react-mentions"),
 ("34","Tribute.js (@mention)","zurb/tribute","tributejs"),
 ("34","Mousetrap","ccampbell/mousetrap","mousetrap"),
 ("34","Fuse.js (见 §31)",None,None),
]
