# 第四批：全框架 UI 组件库清单（为 ui-gallery 建库用）。cat 35=Vue, 36=Svelte/Solid/Qwik/Angular, 37=Web Components/框架无关, 38=纯 CSS/Tailwind 组件集, 39=React 补充
ITEMS = [
    # 35 Vue
    ("35","Element Plus","element-plus/element-plus","element-plus"),
    ("35","Naive UI","tusen-ai/naive-ui","naive-ui"),
    ("35","Vuetify","vuetifyjs/vuetify","vuetify"),
    ("35","PrimeVue","primefaces/primevue","primevue"),
    ("35","Quasar","quasarframework/quasar","quasar"),
    ("35","Nuxt UI","nuxt/ui","@nuxt/ui"),
    ("35","Ant Design Vue","vueComponent/ant-design-vue","ant-design-vue"),
    ("35","Reka UI (ex Radix Vue)","unovue/reka-ui","reka-ui"),
    ("35","shadcn-vue","unovue/shadcn-vue","shadcn-vue"),
    ("35","Vant","youzan/vant","vant"),
    ("35","Arco Design Vue","arco-design/arco-design-vue","@arco-design/web-vue"),
    ("35","TDesign Vue Next","Tencent/tdesign-vue-next","tdesign-vue-next"),
    ("35","Varlet","varletjs/varlet","@varlet/ui"),
    ("35","NutUI","jdf2e/nutui","@nutui/nutui"),
    ("35","Vuestic UI","epicmaxco/vuestic-ui","vuestic-ui"),
    ("35","Headless UI Vue","tailwindlabs/headlessui","@headlessui/vue"),
    ("35","Inkline","inkline/inkline","@inkline/inkline"),
    ("35","Oruga","oruga-ui/oruga","@oruga-ui/oruga-next"),
    ("35","Anu","jd-solanki/anu","anu-vue"),
    ("35","Ionic Vue","ionic-team/ionic-framework","@ionic/vue"),
    ("35","Semi Design Vue (kousum)","DouyinFE/semi-design","@kousum/semi-ui-vue"),
    ("35","Wowerlay / Vue Final Modal (对照)",None,None),
    # 36 Svelte / Solid / Qwik / Angular
    ("36","shadcn-svelte","huntabyte/shadcn-svelte","shadcn-svelte"),
    ("36","Bits UI","huntabyte/bits-ui","bits-ui"),
    ("36","Melt UI","melt-ui/melt-ui","melt"),
    ("36","Skeleton","skeletonlabs/skeleton","@skeletonlabs/skeleton"),
    ("36","Flowbite Svelte","themesberg/flowbite-svelte","flowbite-svelte"),
    ("36","Svelte Material UI","hperrin/svelte-material-ui","svelte-material-ui"),
    ("36","Carbon Components Svelte","carbon-design-system/carbon-components-svelte","carbon-components-svelte"),
    ("36","Attractions","illright/attractions","attractions"),
    ("36","Kobalte (Solid)","kobaltedev/kobalte","@kobalte/core"),
    ("36","solid-ui (Solid shadcn)","stefan-karger/solid-ui",None),
    ("36","SUID (Solid MUI)","swordev/suid","@suid/material"),
    ("36","Hope UI (Solid)","hope-ui/hope-ui","@hope-ui/solid"),
    ("36","Ark UI Solid","chakra-ui/ark","@ark-ui/solid"),
    ("36","Qwik UI","qwikifiers/qwik-ui","@qwik-ui/headless"),
    ("36","Angular Material","angular/components","@angular/material"),
    ("36","PrimeNG","primefaces/primeng","primeng"),
    ("36","NG-ZORRO","NG-ZORRO/ng-zorro-antd","ng-zorro-antd"),
    ("36","Angular CDK","angular/components","@angular/cdk"),
    ("36","Spartan (Angular shadcn)","goetzrobin/spartan","@spartan-ng/brain"),
    ("36","Taiga UI","taiga-family/taiga-ui","@taiga-ui/core"),
    ("36","Nebular","akveo/nebular","@nebular/theme"),
    ("36","Clarity Angular","vmware-clarity/ng-clarity","@clr/angular"),
    ("36","Ionic Angular","ionic-team/ionic-framework","@ionic/angular"),
    # 37 Web Components / 框架无关
    ("37","Shoelace / Web Awesome (见 §19)","shoelace-style/webawesome","@awesome.me/webawesome"),
    ("37","Ionic Core","ionic-team/ionic-framework","@ionic/core"),
    ("37","Material Web (MWC)","material-components/material-web","@material/web"),
    ("37","Vaadin Web Components","vaadin/web-components","@vaadin/button"),
    ("37","Carbon Web Components","carbon-design-system/carbon","@carbon/web-components"),
    ("37","Spectrum Web Components","adobe/spectrum-web-components","@spectrum-web-components/button"),
    ("37","Fluent UI Web Components","microsoft/fluentui","@fluentui/web-components"),
    ("37","SAP UI5 Web Components","SAP/ui5-webcomponents","@ui5/webcomponents"),
    ("37","Nord Design System（仓库不存在）",None,"@nordhealth/components"),
    ("37","Wired Elements","rough-stuff/wired-elements","wired-elements"),
    ("37","Lion (ING)","ing-bank/lion","@lion/ui"),
    ("37","Calcite Components (Esri)","Esri/calcite-design-system","@esri/calcite-components"),
    ("37","Clarity Core","vmware-clarity/core","@cds/core"),
    ("37","Kor UI","kor-ui/kor","@kor-ui/kor"),
    ("37","Cardinal / Oat (对照)",None,None),
    # 38 纯 CSS / Tailwind 组件集 / 设计系统 CSS
    ("38","Bootstrap","twbs/bootstrap","bootstrap"),
    ("38","Bulma","jgthms/bulma","bulma"),
    ("38","Pico CSS","picocss/pico","@picocss/pico"),
    ("38","Foundation","foundation/foundation-sites","foundation-sites"),
    ("38","Tachyons","tachyons-css/tachyons","tachyons"),
    ("38","Water.css","kognise/water.css","water.css"),
    ("38","MVP.css","andybrewer/mvp","mvp.css"),
    ("38","Simple.css","kevquirk/simple.css","simpledotcss"),
    ("38","Open Props (见 §16)","argyleink/open-props","open-props"),
    ("38","Flowbite (Tailwind)","themesberg/flowbite","flowbite"),
    ("38","Preline UI","htmlstreamofficial/preline","preline"),
    ("38","Franken UI","franken-ui/ui","franken-ui"),
    ("38","Basecoat (shadcn HTML)","hunvreus/basecoat","basecoat-css"),
    ("38","UIkit","uikit/uikit","uikit"),
    ("38","Semantic UI / Fomantic UI","fomantic/Fomantic-UI","fomantic-ui"),
    ("38","Materialize","materializecss/materialize","@materializecss/materialize"),
    ("38","Beer CSS","beercss/beercss","beercss"),
    ("38","Spectre.css","picturepan2/spectre","spectre.css"),
    ("38","Milligram","milligram/milligram","milligram"),
    ("38","Cirrus","Spiderpig86/Cirrus","cirrus-ui"),
    ("38","Tailwind Plus / Tailwind UI (商业, 对照)",None,None),
    ("38","Hyper UI","markmead/hyperui",None),
    ("38","Meraki UI","merakiui/merakiui",None),
    ("38","Sailboat UI","sailboatui/sailboatui",None),
    ("38","NES.css","nostalgic-css/NES.css","nes.css"),
    ("38","98.css","jdan/98.css","98.css"),
    ("38","7.css","khang-nd/7.css","7.css"),
    ("38","XP.css","botoxparty/XP.css","xp.css"),
    ("38","Terminal CSS","Gioni06/terminal.css","terminal.css"),
    ("38","PaperCSS","papercss/papercss","papercss"),
    ("38","New.css","xz/new.css","@exampledev/new.css"),
    # 39 React 补充（第一批 §1–§2 未覆盖）
    ("39","PrimeReact","primefaces/primereact","primereact"),
    ("39","Fluent UI React v9","microsoft/fluentui","@fluentui/react-components"),
    ("39","Carbon React","carbon-design-system/carbon","@carbon/react"),
    ("39","React Spectrum","adobe/react-spectrum","@adobe/react-spectrum"),
    ("39","Atlassian Design System",None,"@atlaskit/button"),
    ("39","Shopify Polaris","Shopify/polaris","@shopify/polaris"),
    ("39","Geist (Vercel)","geist-org/geist-ui","@geist-ui/core"),
    ("39","Once UI","once-ui-system/core","@once-ui-system/core"),
    ("39","Flowbite React","themesberg/flowbite-react","flowbite-react"),
    ("39","Ant Design Mobile","ant-design/ant-design-mobile","antd-mobile"),
    ("39","Evergreen (Segment)","segmentio/evergreen","evergreen-ui"),
    ("39","Grommet","grommet/grommet","grommet"),
    ("39","Blueprint (Palantir)","palantir/blueprint","@blueprintjs/core"),
    ("39","Reactstrap","reactstrap/reactstrap","reactstrap"),
    ("39","React Bootstrap","react-bootstrap/react-bootstrap","react-bootstrap"),
    ("39","Semantic UI React","Semantic-Org/Semantic-UI-React","semantic-ui-react"),
    ("39","Theme UI","system-ui/theme-ui","theme-ui"),
    ("39","Rebass (停滞)","rebassjs/rebass","rebass"),
    ("39","Ariakit","ariakit/ariakit","@ariakit/react"),
    ("39","Reach UI (停滞)","reach/reach-ui","@reach/dialog"),
    ("39","Zag.js (状态机)","chakra-ui/zag","@zag-js/react"),
    ("39","Yamada UI","yamada-ui/yamada-ui","@yamada-ui/react"),
    ("39","Cloudscape (AWS)","cloudscape-design/components","@cloudscape-design/components"),
    ("39","Gestalt (Pinterest)","pinterest/gestalt","gestalt"),
    ("39","Primer React (GitHub)","primer/react","@primer/react"),
    ("39","Radix Themes","radix-ui/themes","@radix-ui/themes"),
    ("39","Chakra UI v3 (见 §1)","chakra-ui/chakra-ui","@chakra-ui/react"),
    ("39","NextUI legacy (见 §1 HeroUI)",None,"@nextui-org/react"),
    ("39","Tailwind Variants (见 §16)","heroui-inc/tailwind-variants","tailwind-variants"),
    ("39","Subframe (商业, 对照)",None,None),
    ("39","Saas UI","saas-js/saas-ui","@saas-ui/react"),
    ("39","Tremor (见 §5)","tremorlabs/tremor","@tremor/react"),
    ("39","Douyin Semi (见 §1)","DouyinFE/semi-design","@douyinfe/semi-ui"),
    ("39","Zhihu Zent (停滞)","youzan/zent","zent"),
    ("39","React Suite (rsuite)","rsuite/rsuite","rsuite"),
    ("39","Pixel Retro UI","Dksie09/RetroUI","pixel-retroui"),
    ("39","Neobrutalism components","ekmas/neobrutalism-components",None),
    ("39","Mantine (见 §1)","mantinedev/mantine","@mantine/core"),
    ("39","Material Tailwind","creativetimofficial/material-tailwind","@material-tailwind/react"),
    ("39","Headless UI React (见 §1)","tailwindlabs/headlessui","@headlessui/react"),
    ("39","Ionic React","ionic-team/ionic-framework","@ionic/react"),
    ("39","React95","react95/React95","react95"),
    ("39","Chakra Park UI (见 §1)","chakra-ui/park-ui",None),
]
