# Round 2 candidates (2026-09-05). (category, name, github owner/repo or None, npm package or None)
ITEMS = [
 # 16 CSS-in-JS / 零运行时 CSS / 原子化 CSS
 ("16","Panda CSS","chakra-ui/panda","@pandacss/dev"),
 ("16","vanilla-extract","vanilla-extract-css/vanilla-extract","@vanilla-extract/css"),
 ("16","StyleX (Meta)","facebook/stylex","@stylexjs/stylex"),
 ("16","Pigment CSS (MUI)","mui/pigment-css","@pigment-css/react"),
 ("16","Linaria","callstack/linaria","@linaria/core"),
 ("16","wyw-in-js","Anber/wyw-in-js","@wyw-in-js/transform"),
 ("16","Emotion","emotion-js/emotion","@emotion/react"),
 ("16","styled-components","styled-components/styled-components","styled-components"),
 ("16","UnoCSS","unocss/unocss","unocss"),
 ("16","Tailwind Variants","heroui-inc/tailwind-variants","tailwind-variants"),
 ("16","Lightning CSS","parcel-bundler/lightningcss","lightningcss"),
 ("16","PostCSS","postcss/postcss","postcss"),
 ("16","Open Props","argyleink/open-props","open-props"),
 ("16","Tokenami","tokenami/tokenami","@tokenami/dev"),
 ("16","Stitches (对照)","stitchesjs/stitches","@stitches/react"),
 ("16","Sass (dart-sass)","sass/dart-sass","sass"),
 ("16","Restyle (styled-components 零运行时)","souporserious/restyle","restyle"),
 # 17 构建工具 / 打包器 / 编译器
 ("17","Rspack","web-infra-dev/rspack","@rspack/core"),
 ("17","Rsbuild","web-infra-dev/rsbuild","@rsbuild/core"),
 ("17","Rslib","web-infra-dev/rslib","@rslib/core"),
 ("17","Turbopack (in next.js repo)","vercel/next.js",None),
 ("17","Farm","farm-fe/farm","@farmfe/core"),
 ("17","esbuild","evanw/esbuild","esbuild"),
 ("17","webpack","webpack/webpack","webpack"),
 ("17","Parcel","parcel-bundler/parcel","parcel"),
 ("17","Rollup","rollup/rollup","rollup"),
 ("17","tsdown","rolldown/tsdown","tsdown"),
 ("17","tsup","egoist/tsup","tsup"),
 ("17","SWC","swc-project/swc","@swc/core"),
 ("17","Babel","babel/babel","@babel/core"),
 ("17","Mako (蚂蚁)","umijs/mako","@umijs/mako"),
 ("17","Bun (bundler/runtime)","oven-sh/bun","bun"),
 ("17","Vite Plus","voidzero-dev/vite-plus","vite-plus"),
 ("17","unplugin","unjs/unplugin","unplugin"),
 # 18 包管理 / monorepo / 发布
 ("18","pnpm","pnpm/pnpm","pnpm"),
 ("18","npm CLI","npm/cli","npm"),
 ("18","Yarn Berry","yarnpkg/berry","@yarnpkg/cli"),
 ("18","Turborepo","vercel/turborepo","turbo"),
 ("18","Nx","nrwl/nx","nx"),
 ("18","Lerna","lerna/lerna","lerna"),
 ("18","moon","moonrepo/moon","@moonrepo/cli"),
 ("18","Changesets","changesets/changesets","@changesets/cli"),
 ("18","syncpack","JamieMason/syncpack","syncpack"),
 ("18","Verdaccio","verdaccio/verdaccio","verdaccio"),
 ("18","Deno","denoland/deno",None),
 ("18","Volta","volta-cli/volta",None),
 ("18","fnm","Schniz/fnm",None),
 ("18","corepack","nodejs/corepack","corepack"),
 ("18","publint","publint/publint","publint"),
 ("18","are-the-types-wrong","arethetypeswrong/arethetypeswrong.github.io","@arethetypeswrong/cli"),
 # 19 Web Components / 其他框架对照
 ("19","Lit","lit/lit","lit"),
 ("19","@lit/react",None,"@lit/react"),
 ("19","Stencil","stenciljs/core","@stencil/core"),
 ("19","Web Awesome / Shoelace","shoelace-style/webawesome","@awesome.me/webawesome"),
 ("19","Shoelace (legacy pkg)","shoelace-style/shoelace","@shoelace-style/shoelace"),
 ("19","FAST (Microsoft)","microsoft/fast","@microsoft/fast-element"),
 ("19","Preact","preactjs/preact","preact"),
 ("19","Solid","solidjs/solid","solid-js"),
 ("19","Svelte","sveltejs/svelte","svelte"),
 ("19","Vue","vuejs/core","vue"),
 ("19","Qwik","QwikDev/qwik","@builder.io/qwik"),
 ("19","Angular","angular/angular","@angular/core"),
 ("19","HTMX","bigskysoftware/htmx","htmx.org"),
 ("19","Alpine.js","alpinejs/alpine","alpinejs"),
 ("19","Astro (对照, 已在 §12)","withastro/astro","astro"),
 # 20 3D / Canvas / 游戏
 ("20","three.js","mrdoob/three.js","three"),
 ("20","React Three Fiber","pmndrs/react-three-fiber","@react-three/fiber"),
 ("20","drei","pmndrs/drei","@react-three/drei"),
 ("20","Babylon.js","BabylonJS/Babylon.js","@babylonjs/core"),
 ("20","PixiJS","pixijs/pixijs","pixi.js"),
 ("20","@pixi/react","pixijs/pixi-react","@pixi/react"),
 ("20","Konva","konvajs/konva","konva"),
 ("20","react-konva","konvajs/react-konva","react-konva"),
 ("20","Fabric.js","fabricjs/fabric.js","fabric"),
 ("20","Phaser","phaserjs/phaser","phaser"),
 ("20","p5.js","processing/p5.js","p5"),
 ("20","Theatre.js","theatre-js/theatre","@theatre/core"),
 ("20","OGL","oframe/ogl","ogl"),
 ("20","Rough.js","rough-stuff/rough","roughjs"),
 ("20","tsParticles","tsparticles/tsparticles","@tsparticles/react"),
 ("20","Spline (react)","splinetool/react-spline","@splinetool/react-spline"),
 ("20","Excalidraw","excalidraw/excalidraw","@excalidraw/excalidraw"),
 ("20","tldraw","tldraw/tldraw","tldraw"),
 # 21 地图 / GIS
 ("21","MapLibre GL JS","maplibre/maplibre-gl-js","maplibre-gl"),
 ("21","react-map-gl","visgl/react-map-gl","react-map-gl"),
 ("21","Mapbox GL JS (对照)","mapbox/mapbox-gl-js","mapbox-gl"),
 ("21","Leaflet","Leaflet/Leaflet","leaflet"),
 ("21","react-leaflet","PaulLeCam/react-leaflet","react-leaflet"),
 ("21","OpenLayers","openlayers/openlayers","ol"),
 ("21","deck.gl","visgl/deck.gl","deck.gl"),
 ("21","CesiumJS","CesiumGS/cesium","cesium"),
 ("21","Turf.js","Turfjs/turf","@turf/turf"),
 ("21","Protomaps PMTiles","protomaps/PMTiles","pmtiles"),
 ("21","AntV L7","antvis/L7","@antv/l7"),
 ("21","echarts (地图, 已在 §5)",None,None),
 # 22 实时协作 / CRDT / 实时通信
 ("22","Yjs","yjs/yjs","yjs"),
 ("22","y-websocket","yjs/y-websocket","y-websocket"),
 ("22","Hocuspocus","ueberdosis/hocuspocus","@hocuspocus/server"),
 ("22","Automerge","automerge/automerge","@automerge/automerge"),
 ("22","Loro","loro-dev/loro","loro-crdt"),
 ("22","Liveblocks","liveblocks/liveblocks","@liveblocks/client"),
 ("22","PartyKit / PartyServer","cloudflare/partykit","partyserver"),
 ("22","Socket.IO","socketio/socket.io","socket.io-client"),
 ("22","Zero (Rocicorp)","rocicorp/mono","@rocicorp/zero"),
 ("22","Electric SQL","electric-sql/electric","@electric-sql/client"),
 ("22","Convex (client)","get-convex/convex-js","convex"),
 ("22","Supabase Realtime (js)","supabase/supabase-js","@supabase/supabase-js"),
 ("22","Jazz","garden-co/jazz","jazz-tools"),
 # 23 本地优先 / 浏览器存储
 ("23","TinyBase","tinyplex/tinybase","tinybase"),
 ("23","Dexie.js","dexie/Dexie.js","dexie"),
 ("23","dexie-react-hooks",None,"dexie-react-hooks"),
 ("23","PGlite","electric-sql/pglite","@electric-sql/pglite"),
 ("23","RxDB","pubkey/rxdb","rxdb"),
 ("23","idb","jakearchibald/idb","idb"),
 ("23","idb-keyval","jakearchibald/idb-keyval","idb-keyval"),
 ("23","localForage","localForage/localForage","localforage"),
 ("23","sql.js","sql-js/sql.js","sql.js"),
 ("23","wa-sqlite","rhashimoto/wa-sqlite","wa-sqlite"),
 ("23","PowerSync (web)","powersync-ja/powersync-js","@powersync/web"),
 ("23","InstantDB","instantdb/instant","@instantdb/react"),
 ("23","Triplit","aspen-cloud/triplit","@triplit/client"),
 ("23","Evolu","evoluhq/evolu","@evolu/react"),
 ("23","SQLite Wasm (official)","sqlite/sqlite-wasm","@sqlite.org/sqlite-wasm"),
 ("23","unstorage","unjs/unstorage","unstorage"),
 ("23","Legend-State","LegendApp/legend-state","@legendapp/state"),
]
